name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
